export type VideoType = {
  id: number;
  thumbnail: string;
  title: string;
  channelName: string;
  channelAvatar: string;
  views: number;
  uploadedAt: Date;
  url: string;
  duration: string;
};

const mockVideos = [
  {
    id: 1,
    thumbnail: 'https://img.youtube.com/vi/iXsM6NkEmFc/hqdefault.jpg',
    title: 'Chakra UI Crash Course #1 - Introduction & Setup',
    channelName: 'Dev Simplified',
    channelAvatar: '/avatars/James.png',
    views: 25000,
    uploadedAt: new Date('2024-11-25'),
    url: '/watch?v=1',
    duration: '23:45',
  },
  {
    id: 2,
    thumbnail: 'https://img.youtube.com/vi/hJ873mLhmFQ/hqdefault.jpg',
    title: 'Chakra UI Crash Course | React UI Framework',
    channelName: 'Code Master',
    channelAvatar: '/avatars/James.png',
    views: 34000,
    uploadedAt: new Date('2024-09-15'),
    url: '/watch?v=2',
    duration: '23:45',
  },
  {
    id: 3,
    thumbnail: 'https://img.youtube.com/vi/OjOIL8DJ6sI/hqdefault.jpg',
    title: 'Master Tailwind CSS in 30 Minutes',
    channelName: 'CSS for Beginners',
    channelAvatar: '/avatars/Alan.png',
    views: 120000,
    uploadedAt: new Date('2024-07-01'),
    url: '/watch?v=3',
    duration: '23:45',
  },
  {
    id: 4,
    thumbnail: 'https://img.youtube.com/vi/-LU88pWmzMY/hqdefault.jpg',
    title: 'Monero - How Private Is It Really?',
    channelName: 'Privacy Now',
    channelAvatar: '/avatars/Marcus.png',
    views: 45000,
    uploadedAt: new Date('2024-08-30'),
    url: '/watch?v=4',
    duration: '23:45',
  },
  {
    id: 5,
    thumbnail: 'https://img.youtube.com/vi/QVnkGqEsbK0/hqdefault.jpg',
    title: 'Learn Chakra UI by Building a Todo App',
    channelName: 'Frontend Academy',
    channelAvatar: '/avatars/Alexis.png',
    views: 28000,
    uploadedAt: new Date('2024-10-20'),
    url: '/watch?v=5',
    duration: '23:45',
  },
  {
    id: 6,
    thumbnail: 'https://img.youtube.com/vi/c2_pgcOTUtM/hqdefault.jpg',
    title: 'IQ GPT: Better than ChatGPT?!',
    channelName: 'Crypto Insights',
    channelAvatar: '/avatars/Jessica.png',
    views: 50000,
    uploadedAt: new Date('2024-08-12'),
    url: '/watch?v=5',
    duration: '23:45',
  },
  {
    id: 7,
    thumbnail: 'https://img.youtube.com/vi/cRmMRnjpzAI/hqdefault.jpg',
    title: 'Create Your Own GPT in Under 5 Minutes',
    channelName: 'AI Innovators',
    channelAvatar: '/avatars/Anna.png',
    views: 60000,
    uploadedAt: new Date('2024-06-10'),
    url: '/watch?v=6',
    duration: '23:45',
  },
  {
    id: 8,
    thumbnail: 'https://img.youtube.com/vi/jHv63Uvk5VA/hqdefault.jpg',
    title: 'Complete ChatGPT Tutorial',
    channelName: 'AI Experts',
    channelAvatar: '/avatars/Skylar.png',
    views: 90000,
    uploadedAt: new Date('2024-07-05'),
    url: '/watch?v=7',
    duration: '23:45',
  },
  {
    id: 9,
    thumbnail: 'https://img.youtube.com/vi/kCc8FmEb1nY/hqdefault.jpg',
    title: "Let's Build GPT: From Scratch, In Code",
    channelName: 'AI Builders',
    channelAvatar: '/avatars/Skylar.png',
    views: 110000,
    uploadedAt: new Date('2024-05-20'),
    url: '/watch?v=8',
    duration: '23:45',
  },
  {
    id: 10,
    thumbnail: 'https://img.youtube.com/vi/XqZsoesa55w/hqdefault.jpg',
    title: 'Building a YouTube Clone with Next.js',
    channelName: 'Dev Creator',
    channelAvatar: '/avatars/Jessica.png',
    views: 156000,
    uploadedAt: new Date('2024-02-15'),
    url: '/watch?v=9',
    duration: '23:45',
  },
  {
    id: 11,
    thumbnail: 'https://img.youtube.com/vi/3pXVHRT-amw/hqdefault.jpg',
    title: 'Next.js 13: Mastering the New App Router',
    channelName: 'James Gouse',
    channelAvatar: '/avatars/James.png',
    views: 87000,
    uploadedAt: new Date('2024-09-01'),
    url: '/watch?v=11',
    duration: '47:20',
  },
  {
    id: 12,
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    title: 'State Management in React with Redux Toolkit',
    channelName: 'Alan Cooper',
    channelAvatar: '/avatars/Alan.png',
    views: 32000,
    uploadedAt: new Date('2024-08-10'),
    url: '/watch?v=12',
    duration: '34:18',
  },
  {
    id: 13,
    thumbnail: 'https://img.youtube.com/vi/Z5iWr6Srsj8/hqdefault.jpg',
    title: 'Tailwind CSS: Build Responsive Layouts Fast',
    channelName: 'Marcus Levin',
    channelAvatar: '/avatars/Marcus.png',
    views: 54000,
    uploadedAt: new Date('2024-10-05'),
    url: '/watch?v=13',
    duration: '28:45',
  },
  {
    id: 14,
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    title: 'Learn TypeScript in 60 Minutes',
    channelName: 'Alexis Sears',
    channelAvatar: '/avatars/Alexis.png',
    views: 95000,
    uploadedAt: new Date('2024-11-15'),
    url: '/watch?v=14',
    duration: '1:00:30',
  },
  {
    id: 15,
    thumbnail: 'https://img.youtube.com/vi/sBws8MSXN7A/hqdefault.jpg',
    title: 'Building a Todo App with React and Firebase',
    channelName: 'Jesica Lambert',
    channelAvatar: "/avatars/Jessica.png",
    views: 71000,
    uploadedAt: new Date('2024-09-25'),
    url: '/watch?v=15',
    duration: '42:50',
  },
  {
    id: 16,
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    title: 'Advanced Animations with Framer Motion',
    channelName: 'Anna White',
    channelAvatar: '/avatars/Anna.png',
    views: 62000,
    uploadedAt: new Date('2024-07-15'),
    url: '/watch?v=16',
    duration: '37:22',
  },
  {
    id: 17,
    thumbnail: 'https://img.youtube.com/vi/Ke90Tje7VS0/hqdefault.jpg',
    title: "React 18: What's New and How to Use It",
    channelName: 'Skylar Dias',
    channelAvatar: '/avatars/Skylar.png',
    views: 113000,
    uploadedAt: new Date('2024-06-05'),
    url: '/watch?v=17',
    duration: '1:12:45',
  },
  {
    id: 18,
    thumbnail: 'https://img.youtube.com/vi/3pXVHRT-amw/hqdefault.jpg',
    title: 'Build a Full-Stack App with Next.js and Prisma',
    channelName: 'James Gouse',
    channelAvatar: '/avatars/James.png',
    views: 99000,
    uploadedAt: new Date('2024-05-20'),
    url: '/watch?v=18',
    duration: '58:30',
  },
  {
    id: 19,
    thumbnail: 'https://img.youtube.com/vi/QFaFIcGhPoM/hqdefault.jpg',
    title: 'Understanding CSS Grid: A Practical Guide',
    channelName: 'Alan Cooper',
    channelAvatar: '/avatars/Alan.png',
    views: 64000,
    uploadedAt: new Date('2024-04-12'),
    url: '/watch?v=19',
    duration: '45:18',
  },
  {
    id: 20,
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    title: 'JavaScript Async/Await Explained',
    channelName: 'Marcus Levin',
    channelAvatar: '/avatars/Marcus.png',
    views: 125000,
    uploadedAt: new Date('2024-03-03'),
    url: '/watch?v=20',
    duration: '32:10',
  },
  {
    id: 21,
    thumbnail: 'https://img.youtube.com/vi/f8qBeaGe2S4/hqdefault.jpg',
    title: 'React Hooks: The Complete Guide',
    channelName: 'Alexis Sears',
    channelAvatar: '/avatars/Alexis.png',
    views: 87000,
    uploadedAt: new Date('2024-02-15'),
    url: '/watch?v=21',
    duration: '41:25',
  },
  {
    id: 22,
    thumbnail: 'https://img.youtube.com/vi/lJIrF4YjHfQ/hqdefault.jpg',
    title: 'Introduction to GraphQL for Beginners',
    channelName: 'Jesica Lambert',
    channelAvatar: '/avatars/Jesica.png',
    views: 48000,
    uploadedAt: new Date('2024-02-10'),
    url: '/watch?v=22',
    duration: '50:55',
  },
  {
    id: 23,
    thumbnail: 'https://img.youtube.com/vi/Z5iWr6Srsj8/hqdefault.jpg',
    title: 'Understanding the Virtual DOM in React',
    channelName: 'Anna White',
    channelAvatar: '/avatars/Anna.png',
    views: 61000,
    uploadedAt: new Date('2024-01-20'),
    url: '/watch?v=23',
    duration: '39:40',
  },
  {
    id: 24,
    thumbnail: 'https://img.youtube.com/vi/COk73cpQbFQ/hqdefault.jpg',
    title: 'Deploying Next.js Apps on Vercel',
    channelName: 'Skylar Dias',
    channelAvatar: '/avatars/Skylar.png',
    views: 57000,
    uploadedAt: new Date('2023-12-18'),
    url: '/watch?v=24',
    duration: '33:12',
  },
  {
    id: 25,
    thumbnail: 'https://img.youtube.com/vi/PKwu15ldZ7k/hqdefault.jpg',
    title: 'Building Scalable APIs with Node.js',
    channelName: 'James Gouse',
    channelAvatar: '/avatars/James.png',
    views: 91000,
    uploadedAt: new Date('2023-12-02'),
    url: '/watch?v=25',
    duration: '1:05:22',
  },
  {
    id: 26,
    thumbnail: 'https://img.youtube.com/vi/Z5iWr6Srsj8/hqdefault.jpg',
    title: 'Creating Reusable Components in React',
    channelName: 'Alan Cooper',
    channelAvatar: '/avatars/Alan.png',
    views: 48000,
    uploadedAt: new Date('2023-11-15'),
    url: '/watch?v=26',
    duration: '28:50',
  },
  {
    id: 27,
    thumbnail: 'https://img.youtube.com/vi/3pXVHRT-amw/hqdefault.jpg',
    title: 'Server-Side Rendering with Next.js',
    channelName: 'Marcus Levin',
    channelAvatar: '/avatars/Marcus.png',
    views: 71000,
    uploadedAt: new Date('2023-11-02'),
    url: '/watch?v=27',
    duration: '36:30',
  },
  {
    id: 28,
    thumbnail: 'https://img.youtube.com/vi/W6NZfCO5SIk/hqdefault.jpg',
    title: 'JavaScript Basics: A Beginner’s Guide',
    channelName: 'Alexis Sears',
    channelAvatar: '/avatars/Alexis.png',
    views: 85000,
    uploadedAt: new Date('2023-10-25'),
    url: '/watch?v=28',
    duration: '22:18',
  },
  {
    id: 29,
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    title: 'Introduction to Docker for Developers',
    channelName: 'Jesica Lambert',
    channelAvatar: '/avatars/Jesica.png',
    views: 67000,
    uploadedAt: new Date('2023-09-18'),
    url: '/watch?v=29',
    duration: '43:40',
  },
];

export default mockVideos;
